# Generated by Django 2.2.15 on 2020-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=16, verbose_name='动物的名称'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
