# Generated by Django 2.2.16 on 2020-10-13 01:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20200819_1635'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
    ]
